import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import BootstrapClient from './components/BootstrapClient'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <div className="d-flex justify-content-center">
            <div>
              <div className="p-4 rounded mt-4 underlined">
                <h1>
                  <u>Serverless Content Management System</u>
                </h1>
              </div>
            </div>
          </div>
          {children}
        </section>
      </body>
      <BootstrapClient />
    </html>
  )
}
